nimblehq/nimble-medium-ios

.gitignore
.swiftlint.yml
NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Modules/Home/HomeView.swift
NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Supports/Helpers/Typealias.swift
Podfile
Podfile.lock

Resolved #20 
When starting a new project, the project localization should be setup properly for removing the usage of hardcoded texts and thus easily supporting a new language in the future.
- Add R.swift dependency thru Cocoapod
- Add localizable file
- Ignore R.generated.swift in swiftlint & git
Display a localized text

[#20] Setup project localization

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeaderView.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuView.swift

Resolved #11
When user doesn't login to the app yet, the users will be able to see the left menu header with some default information about the app.
https://user-images.githubusercontent.com/70877098/130425740-8b8dc396-428f-475a-b545-292cf0ba1159.mov

[#11] As a user, I can view the default left menu header when not logged in

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
NimbleMedium/Sources/Presentation/Modules/Login/LoginView.swift
NimbleMedium/Sources/Presentation/Modules/Login/LoginViewModel.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActionItemView.swift

Resolved #24 
For the existing users of the application that don't login yet, they should be able to login into the application for being able use more features and manage personal contents.

[#24] As a user, I can login to the application

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium.xcodeproj/xcshareddata/xcschemes/NimbleMedium Staging.xcscheme
NimbleMedium.xcodeproj/xcshareddata/xcschemes/NimbleMedium.xcscheme
Podfile.lock

Add Debug configuration for Staging and Production schemes so that we can still build the application in Debug mode.
No visual changes, just under the hood optimization.

[Chore] Add Debug configuration for Staging and Production schemes

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Factories/Application/DependencyFactory+ViewModelFactoryProtocol.swift
NimbleMedium/Sources/Factories/Presentation/ViewModelFactoryProtocol.swift
NimbleMedium/Sources/Presentation/Modules/Login/LoginView.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModel.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuViewModel.swift
NimbleMedium/Sources/Presentation/Modules/Signup/SignupView.swift
NimbleMedium/Sources/Presentation/Views/AppMainButton.swift
NimbleMedium/Sources/Presentation/Views/AuthSecureFieldView.swift
NimbleMedium/Sources/Presentation/Views/AuthTextFieldView.swift

Resolved #26 
For the new users of the application, they should be able to see the `Signup` screen for being able to create a new account, explore and use more features from the application.
https://user-images.githubusercontent.com/70877098/130801134-0b4b9259-5c84-41f8-9a25-61c26f451b45.mov

[#26] As a user, I can signup from the left menu

---

.github/workflows/deploy_testflight.yml
NimbleMedium.xcodeproj/project.pbxproj

Resolved #4
When starting a new project, the CD pipeline should be setup properly for automatically testing to validate if changes to the codebase are correct and stable for immediate autonomous deployment to a production environment.
- Add app icon due to it's required to upload into AppStore
- Add Deploy to TestFlight github action
- Update constants for Fastlane
TestFlight
Github Action

[#4] Set up CD pipeline for production releases

---

.github/workflows/lint_and_unit_test.yml
.gitignore
.slather.yml
Gemfile
Gemfile.lock
NimbleMedium.xcodeproj/xcshareddata/xcschemes/NimbleMedium Staging.xcscheme

Resolved #126 
Setup Codecov
- Use `slasher` to convert code coverage data to xml
- Upload converted xml to Codecov
-

[#126] Setup Codecov

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/AuthRequestConfiguration.swift
NimbleMedium/Sources/Data/Repositories/Auth/AuthRepository.swift
NimbleMedium/Sources/Domain/Repositories/Auth/AuthRepositoryProtocol.swift
NimbleMedium/Sources/Domain/UseCases/SignupUseCase.swift
NimbleMedium/Sources/Factories/Application/DependencyFactory+UseCaseFactoryProtocol.swift
NimbleMedium/Sources/Factories/Domain/UseCaseFactoryProtocol.swift

Resolved #33
The users will be able to create a new account by using the signup API from server.
```
{
"user":{
"username": "Jacob",
"email": "jake@jake.jake",
"password": "jakejake"
}
}
````
```
{
"user": {
"email": "jake@jake.jake",
"token": "jwt.token.here",
"username": "jake",
"bio": "I work at statefarm",
"image": null
}
}
```
https://user-images.githubusercontent.com/70877098/131612980-9e990454-13c9-4f36-811d-c429b760dc7e.mov
Full success request/response log:
```
---------------------
POST 'https://conduit.productionready.io/api/users':
cURL:
$ curl -v \
-X POST \
-H "Accept-Encoding: br;q=1.0, gzip;q=0.9, deflate;q=0.8" \
-H "User-Agent: Nimble Medium - Staging/1.0.0 (co.nimblehq.nimble-medium-stag; build:1; iOS 14.7.1) Alamofire/5.4.3" \
-H "Accept-Language: en-VN;q=1.0, …
```

[#33] As a user, I can signup for a new account

---

NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Sources/Factories/Application/DependencyFactory+ViewModelFactoryProtocol.swift
NimbleMedium/Sources/Presentation/Modules/Login/LoginView.swift
NimbleMedium/Sources/Presentation/Modules/Login/LoginViewModel.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModel.swift
NimbleMedium/Sources/Presentation/Modules/Signup/SignupView.swift
NimbleMedium/Sources/Presentation/Modules/Signup/SignupViewModel.swift

Resolved #31
For the new users of the application, they should be able to signup and create a new account for being able to explore and use more features from the application.
- Request signup - success case:
https://user-images.githubusercontent.com/70877098/131616038-6358746a-d8e8-4e98-be20-67eda8dd481c.mov
- Navigate to Login screen:
https://user-images.githubusercontent.com/70877098/131615959-e3936f26-7206-406e-b14f-651f762b9dac.mov

[#31] As a user, I can signup for a new account

---

NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderView.swift

Resolved #38
Once the users logged in the application successfully, opening the left navigation menu will show a brief summary of the user information in the menu header, which includes: the user avatar and the username.

[#38] As a user, I can see my profile briefing in the left menu header

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderViewModel.swift
NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView+UIModel.swift
NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift

Resolved #62
When the users don't login to the app yet, they will still be able to view other author profile by selecting the author region in the `Article Details` screen.

[#62] Implement UI for User Profile screen

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentRow/FeedCommentRow+UIModel.swift
NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentRow/FeedCommentRow.swift
NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentRow/FeedCommentRowViewModel.swift
NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentsView.swift
NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentsViewModel.swift
NimbleMedium/Sources/Presentation/Modules/FeedDetail/FeedDetailView.swift
NimbleMedium/Sources/Presentation/Modules/FeedDetail/FeedDetailViewModel.swift
NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/FeedComments/FeedCommentRow/FeedCommentRowViewModelSpec.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/FeedComments/FeedCommentsViewModelSpec.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/FeedDetail/FeedDetailViewModelSpec.swift

Resolved #105
Resolved #28
- Integrate Feed Comments screen
- Link FeedDetail with Feed Comments screen
https://user-images.githubusercontent.com/17875522/134609125-b49bde8a-23d3-4812-8078-8ef7d9c5498a.mov
#151

[#105] [#28] As a user, I can see the list of comments of an article

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Domain/UseCases/Article/GetListArticlesUseCase.swift
NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
NimbleMediumTests/Sources/Specs/Domain/UseCases/Article/GetListArticlesUseCaseSpec.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/FeedComments/FeedCommentRow/FeedCommentRowViewModelSpec.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedRow/FeedRowViewModelSpec.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift

Refactor ListArticlesUseCase.
- Update from ListArticlesUseCase to GetListArticlesUseCase for naming consistency with other use cases in the app that the first letter should be a verb.
- Update to use execute function naming.
No visual changes, just under the hood optimization 🛠

[Chore] Refactor ListArticlesUseCase

---

NimbleMedium/Configurations/Plists/Info.plist

Resolved #161 
UI: Home Screen and detail post screen have black background. Login and signup screen showing empty text fields and white texts instead of black.
https://user-images.githubusercontent.com/70877098/135197713-a8ba4c0c-7ac8-47a0-a4fe-128b425571d1.MP4
- The app doesn't support dark mode yet. Need to disable dark mode and always showing the app as light mode regardless of the system theme settings.
The app shows as light mode as normally:
https://user-images.githubusercontent.com/70877098/135198394-958f09cf-175b-4904-814c-14fc08bae20f.mov

[#161] Disable support for dark mode since the app doesn't handle it yet

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Data/Models/CodableUser.swift
NimbleMedium/Sources/Data/NetworkAPI/Core/AuthenticatedNetworkAPI.swift
NimbleMedium/Sources/Data/NetworkAPI/Core/AuthenticatedNetworkAPIProtocol.swift
NimbleMedium/Sources/Data/NetworkAPI/Core/NetworkAPIError.swift
NimbleMedium/Sources/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
NimbleMedium/Sources/Data/NetworkAPI/Core/RequestConfiguration.swift
NimbleMedium/Sources/Data/NetworkAPI/Interceptors/AuthenticatedInterceptor.swift
NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/AuthRequestConfiguration.swift
NimbleMedium/Sources/Data/Repositories/Auth/AuthRepository.swift
NimbleMedium/Sources/Domain/Repositories/Auth/AuthRepositoryProtocol.swift
NimbleMedium/Sources/Domain/UseCases/User/GetCurrentUserUseCase.swift
NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
NimbleMediumTests/Resources/JSON/user.json
NimbleMediumTests/Sources/Dummy/Data/Models/APIUserResponse+Dummy.swift
NimbleMediumTests/Sources/Specs/Domain/UseCases/User/GetCurrentUserUseCaseSpec.swift

Resolved #52
Once authenticated, the users will be able to get their own profile from server.
Request log with tokens (no response log for now due to server issue): 
```
GET 'https://conduit.productionready.io/api/user':
cURL:
$ curl -v \
-X GET \
-H "Accept-Language: en-VN;q=1.0, vi-VN;q=0.9, th-VN;q=0.8" \
-H "Accept-Encoding: br;q=1.0, gzip;q=0.9, deflate;q=0.8" \
-H "User-Agent: Nimble Medium - Staging/1.2.0 (co.nimblehq.nimble-medium-stag; build:1; iOS 14.8.0) Alamofire/5.4.4" \
-H "Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MjAxNTEwLCJ1c2VybmFtZSI6Ik1pa2V5IiwiZXhwIjoxNjM3MzE5MTc0fQ.K5DxymXZrSPdndbLga7YQSunB4HLDHmnU0MPqeQ2V3U" \
"https://conduit.productionready.io/api/user"
2021-09-29 14:41:39.342214+0700 Nimble Medium - Staging[2930:2067420] [connection] …
```

[#52] As a user, I can get my own profile information

---

Gemfile
Gemfile.lock
NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Domain/UseCases/Article/GetCreatedArticlesUseCase.swift
NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMediumTests/Sources/Specs/Domain/UseCases/Article/GetCreatedArticlesUseCaseSpec.swift

Resolved #66
Add GetCreatedArticles use case
- Update cocoapod version in `Gemfile` to match with version in `Podfile.lock`
Request
```
*** Overview *** 
URL https://conduit.productionready.io/api/articles?author=markg&limit=25
Method GET
Response Code -
Request Start Time Sep 28 2021 - 15:14:28
Duration 848ms
*** Request Header *** 
User-Agent Nimble Medium - Staging/1.2.0 (co.nimblehq.nimble-medium-stag; build:1; iOS 14.5.0) Alamofire/5.4.4
Accept-Language en;q=1.0
Accept-Encoding br;q=1.0, gzip;q=0.9, deflate;q=0.8
*** Request Body *** 
-
*** Response Header *** 
-
*** Response Body *** 
-
------------------------------------------------------------------------
------------------------------------------------------------------------ …
```

[66] As a user, I can see the list of created articles from the profile screen

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Constants/Constants+API.swift
NimbleMedium/Sources/Domain/UseCases/Auth/LoginUseCase.swift
NimbleMedium/Sources/Domain/UseCases/Auth/SignupUseCase.swift
NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentsViewModel.swift
NimbleMedium/Sources/Presentation/Modules/FeedDetail/FeedDetailViewModel.swift
NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
NimbleMedium/Sources/Presentation/Modules/Login/LoginViewModel.swift
NimbleMedium/Sources/Presentation/Modules/Signup/SignupViewModel.swift
NimbleMedium/Sources/Supports/Extensions/Rx/ObservableType+Void.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/Login/LoginViewModelSpec.swift

Refactor Login and Sign ViewModels and add mapToVoid extension for consistency with other places.
- Update Login and Signup ViewModels to use private extensions with for use case triggering.
- Use type aliases for the tuple declarations.
- Add mapToVoid extension and apply to all places in the application.
- Refactor the use cases's function names to` execute` for  Login and Signup use cases.
- Force to use: `https://realworld-temp-api.herokuapp.com/api` since the production endpoint: `https://conduit.productionready.io/api` is completely unusable with Authentication features.
No visual changes, just under the hood optimization 🛠

[Chore] Refactor Login and Sign ViewModels and add mapToVoid extension

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView+UIModel.swift
NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift
NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileViewModel.swift
NimbleMedium/Sources/Presentation/Views/AuthorView.swift
NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/UserProfile/UserProfileViewModelSpec.swift

Resolved #64
When the users don't login to the app yet, they will still be able to view other author profile by selecting the author region in the `Article Details` screen.
https://user-images.githubusercontent.com/70877098/135831234-49d5579a-9df0-4f41-812c-4263a572161f.mov
Unit tests added:
With coverage report:

[#64] As a user, I can view other author profile details from the article details screen when not logged in

---

NimbleMedium/Sources/Domain/Repositories/User/UserSessionRepositoryProtocol.swift
NimbleMedium/Sources/Domain/UseCases/User/GetCurrentUserUseCase.swift
NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuViewModel.swift
NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileViewModel.swift
NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
NimbleMediumTests/Sources/Specs/Domain/UseCases/User/GetCurrentUserUseCaseSpec.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/UserProfile/UserProfileViewModelSpec.swift

Resolved #57
When the users logged in the application successfully, they will be able to view their profile details with a `My Profile` option in the left menu from `Home` Screen.
https://user-images.githubusercontent.com/70877098/136324407-f4474ddc-748a-4209-b528-5db0f0bee491.MP4

[#57] As a user, I can view my own profile details

---

NimbleMedium/Sources/Constants/SystemImageName.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderView.swift

Resolved #39
Once the users logged in the application successfully, they can edit their profile from the menu header if needed.

[#39] As a user, I can update my profile from the left menu header

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Sources/Data/Repositories/User/UserSessionRepository.swift
NimbleMedium/Sources/Domain/Repositories/User/UserSessionRepositoryProtocol.swift
NimbleMedium/Sources/Domain/UseCases/Auth/LogoutUseCase.swift
NimbleMedium/Sources/Domain/UseCases/User/GetCurrentSessionUseCase.swift
NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMedium/Sources/Presentation/Modules/Login/LoginView.swift
NimbleMedium/Sources/Presentation/Modules/Login/LoginViewModel.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModel.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuViewModel.swift
NimbleMedium/Sources/Presentation/Modules/Signup/SignupView.swift
NimbleMedium/Sources/Presentation/Modules/Signup/SignupViewModel.swift
NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
NimbleMediumTests/Sources/Specs/Domain/UseCases/Auth/LogoutUseCaseSpec.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModelSpec.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderViewModelSpec.swift

Resolved #42
When the users logged in the application successfully, they will be able to logout the application with a `Logout` option in the left menu from `Home` Screen.
https://user-images.githubusercontent.com/70877098/136774599-b2a2154e-177c-474f-8797-244b347aa781.mov
- LogoutUseCase:
- SideMenuActionsViewModel:

[#42] As a user, I can logout from the left menu

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMedium/Sources/Presentation/Modules/EditProfile/EditProfileView+UIModel.swift
NimbleMedium/Sources/Presentation/Modules/EditProfile/EditProfileView.swift
NimbleMedium/Sources/Presentation/Modules/EditProfile/EditProfileViewModel.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModel.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderViewModel.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuView.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuMain/SideMenuViewModel.swift
NimbleMedium/Sources/Presentation/Views/AppTextView.swift
NimbleMedium/Sources/Supports/Extensions/Foundation/JSONDecoder+Default.swift
NimbleMedium/Sources/Supports/Extensions/Foundation/String+EmptyCheck.swift
NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/EditProfile/EditProfileViewModelSpec.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/SideMenu/SideMenuMain/SideMenuViewModelSpec.swift

Resolved #61
When the users logged in the application successfully, they will be able to update their profile details with the `Edit Profile` button in the left menu header from `Home` Screen.
https://user-images.githubusercontent.com/70877098/137072395-b593bfff-b39e-4341-9c8f-14366a94ee10.mov
Tests passed for `EditProfileViewModel`:
Tests passed for `SideMenuViewModel `:

[#61] As a user, I can update my own profile details

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/ArticleRequestConfiguration.swift
NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/AuthRequestConfiguration.swift
NimbleMedium/Sources/Data/Repositories/Article/ArticleRepository.swift
NimbleMedium/Sources/Domain/Parameters/CreateArticleParameters.swift
NimbleMedium/Sources/Domain/Parameters/UpdateCurrentUserParameters.swift
NimbleMedium/Sources/Domain/Repositories/Article/ArticleRepositoryProtocol.swift
NimbleMedium/Sources/Domain/UseCases/Article/CreateArticleUseCase.swift
NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMedium/Sources/Supports/Extensions/Foundation/Encodable+Dictionary.swift
NimbleMediumTests/Sources/Dummy/Data/Models/CreateArticleParameters+Dummy.swift
NimbleMediumTests/Sources/Specs/Data/Repositories/Article/ArticleRepositorySpec.swift
NimbleMediumTests/Sources/Specs/Domain/UseCases/Article/CreateArticleUseCaseSpec.swift

Resolved #81
Once authenticated, the users will be able to publish a newly created article to the server.
```
{
"article": {
"title": "How to train your dragon",
"description": "Ever wonder how?",
"body": "You have to believe",
"tagList": ["reactjs", "angularjs", "dragons"]
}
}
````
```
{
"article": {
"slug": "how-to-train-your-dragon",
"title": "How to train your dragon",
"description": "Ever wonder how?",
"body": "It takes a Jacobian",
"tagList": ["dragons", "training"],
"createdAt": "2016-02-18T03:22:56.637Z",
"updatedAt": "2016-02-18T03:48:35.824Z",
"favorited": false,
"favoritesCount": 0,
"author": {
"username": "jake",
"bio": "I work at statefarm",
"image": "https://i.stack.imgur.com/xHWG8.jpg",
"following": false
}
}
}
```
Sent request:
```
POST …
```

[#81] As a user, I can create a new article

---

NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Sources/Constants/SystemImageName.swift
NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift

Resolved #91
Add delete article details button in Article Detail screen
https://user-images.githubusercontent.com/17875522/139012916-16f27d00-f90b-4748-a2ac-0c7eafdf9aa5.mov

[#91] As a user, I can delete my article from the article details screen

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailViewModel.swift
NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsTab/FeedsTabView.swift
NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
NimbleMediumTests/Sources/Dummy/Data/Models/APIUserResponse+Dummy.swift
NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/ArticleDetail/ArticleDetailViewModelSpec.swift
NimbleMediumTests/Sources/Utilities/String+Data.swift

Resolved #94
Integrate delete article in Article Detail screen
Success
https://user-images.githubusercontent.com/17875522/139024156-afe4a023-b788-4a0d-9d5f-afdb00b70ac2.mov
Failure
https://user-images.githubusercontent.com/17875522/139024208-16b1558e-2938-47a7-a814-4d9ff6358e1f.mov

[#94] As a user, I can delete my article from the article details screen

---

NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift

Resolved #95 
Add Edit Toolbar Item in Article Detail screen

[#95] As a user, I can edit my article from the article details screen

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Constants/SystemImageName.swift
NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRow.swift
NimbleMedium/Sources/Presentation/Views/FavouriteButton.swift

Resolved #86
Add Favourite Button UI into Home screen & Profile screen
Home screen
| Normal  | Selected |
| ------------- | ------------- |
| ![Screen Shot 2021-10-29 at 10 32 12](https://user-images.githubusercontent.com/17875522/139372565-b999f54b-8b1d-4a7e-b591-9fed075895de.png) | ![Screen Shot 2021-10-29 at 10 35 17](https://user-images.githubusercontent.com/17875522/139372657-c4934048-7fbe-4a3c-9742-ad35bc8e3efa.png)  |
Favourited screen
| Normal  | Selected |
| ------------- | ------------- |
| ![Screen Shot 2021-10-29 at 10 46 30](https://user-images.githubusercontent.com/17875522/139372767-6750c6d4-c0e0-40dc-ae88-455e7241dd8c.png) | ![Screen Shot 2021-10-29 at 10 43 58](https://user-images.githubusercontent.com/17875522/139372782-3697b1dc-aeb2-473c-ad56-e772d0b16001.png)  |

[#86][#48] Add Favourite Button UI

---

NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift

Resolved #49
Add Favourite Button UI in Article Detail screen
| Normal  | Selected |
| ------------- | ------------- |
| ![Screen Shot 2021-10-29 at 11 01 03](https://user-images.githubusercontent.com/17875522/139386924-832bb40d-abbd-47bf-b779-ca7c5ff6bd3b.png) | ![Screen Shot 2021-10-29 at 11 02 22](https://user-images.githubusercontent.com/17875522/139386893-83d663da-273b-487d-aef5-76caf399ee38.png)  |

[#49] Add Favourite Button UI in Article Detail screen

---

NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRow+UIModel.swift
NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRow.swift
NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRowViewModel.swift
NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/ArticleRow/ArticleRowViewModelSpec.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsTab/FeedsTabViewModelSpec.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift

Resolved #88
Resolved #90
Integrate Favourite Button in Home and Profile screen
Home screen
https://user-images.githubusercontent.com/17875522/139621054-15fd2446-c10e-4205-809f-43cc68647c6a.mov
Profile screen
https://user-images.githubusercontent.com/17875522/139621093-2f0e22d5-b534-412e-b825-e9ce1a16cb27.mov

[#88] [#90] As a user, I can toggle to update an article as my favorites from the home/profile screen

---

NimbleMedium/Sources/Constants/SystemImageName.swift
NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView+UIModel.swift
NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailViewModel.swift
NimbleMedium/Sources/Supports/Extensions/SwiftUI/View+OnReceive.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/ArticleDetail/ArticleDetailViewModelSpec.swift

Resolved #89 
Integrate Favourite Button in Article Detail screen
https://user-images.githubusercontent.com/17875522/139643066-3e0cac57-0b0b-4741-a0cd-af910a958254.mov

[#89] Integrate Favourite Button in Article Detail screen

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Application/App.swift
NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
NimbleMedium/Sources/Presentation/Modules/Shared/UserSessionViewModel.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsView.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModel.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/Shared/UserSessionViewModelSpec.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/SideMenu/SideMenuActions/SideMenuActionsViewModelSpec.swift

Resolved #208 
The Home screen won't update tabs when a user login/logout
- When login: Home screen shows up 2 tabs: Your Feeds & Global Feeds
- When logout: Home screen only shows the content of Global Feeds tab
- Introduce a shared viewModel: `UserSessionViewModel` for handling the shared session.
- Update unit tests
https://user-images.githubusercontent.com/70877098/139646083-dd7a6a52-446d-4904-b409-c50218f366cd.MP4
All tests are passed:

[#208] Fix: Home screen won't update tabs when a user login/logout

---

NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift

Resolved #98 
Integrate go to Edit Article screen
https://user-images.githubusercontent.com/17875522/139804364-afb57a16-94b9-4090-bd72-d164de1b277b.mov

[#98] As a user, I can edit my article from the article details screen

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailViewModel.swift
NimbleMedium/Sources/Presentation/Modules/EditArticle/EditArticleView+UIModel.swift
NimbleMedium/Sources/Presentation/Modules/EditArticle/EditArticleView.swift
NimbleMedium/Sources/Presentation/Modules/EditArticle/EditArticleViewModel.swift
NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsTab/FeedsTabView.swift
NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/EditArticle/EditArticleViewModelSpec.swift

Resolved #99
Integrate Edit Article screen
https://user-images.githubusercontent.com/17875522/139805533-a6a3f46e-5721-4d53-94e3-ed3111b537af.mov

[#99] As a user, I can edit my own article

---

NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Sources/Constants/SystemImageName.swift
NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentsView.swift

Resolved #100 
Create comment input UI
When the keyboard is up

[#100] As a user, I can comment on an article in the comments history screen

---

NimbleMedium/Sources/Constants/SystemImageName.swift
NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentRow/ArticleCommentRow.swift

Resolved #106
When the users login the application successfully, they can delete their own comment from any article in the `Comments History` screen.

[#106]  As a user, I can delete my comment on an article in the comments history screen

---

NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentsView.swift
NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentsViewModel.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/ArticleComments/ArticleCommentsViewModelSpec.swift

Resolved #104
Integrate create comment
https://user-images.githubusercontent.com/17875522/140251988-2c2d2c14-79b1-4e33-8723-6ea01b2aef28.mov

[#104] As a user, I can comment on an article in the comments history screen

---

NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentRow/ArticleCommentRow+UIModel.swift
NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentRow/ArticleCommentRow.swift
NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentRow/ArticleCommentRowViewModel.swift
NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentsViewModel.swift
NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/ArticleComments/FeedCommentRow/ArticleCommentRowViewModelSpec.swift

Resolved #108
Integrate delete comment
https://user-images.githubusercontent.com/17875522/140474022-e6732cd5-87f5-4e99-8ed7-7c49ad5d3fd8.mov

[#108] As a user, I can delete my comment on an article in the comments history screen

---

NimbleMedium/Sources/Injection/Resolver+Injection.swift

Resolved #238
Current we are using .cached for ViewModel mostly for keeping the same instance when injecting. But we can use .shared to correctly use it in case we need to apply it for parent-child ViewModel relationship cases.
Update to use .shared scope for parent/child relationships view models
No visual change, just under the hood optimization and the app works normally. 🛠

[#238] Chore: Refactor Resolver library scope correctly for ViewModel

---

NimbleMedium/Sources/Injection/Resolver+Injection.swift

Resolved #237 
Refactor Resolve library to use `.register` instead of `.implement` for correct object generation per interface.
Use `.register` instead of `.implement` for Resolver injections.
No visual change, just under the hood optimization and the app works normally. 🛠

[#237]  Refactor Resolve library to register correctly

---

NimbleMedium/Sources/Presentation/Modules/Login/LoginView.swift
NimbleMedium/Sources/Presentation/Modules/Signup/SignupView.swift
NimbleMedium/Sources/Presentation/Views/AppTextField.swift

Resolved #243 
Username & Email input got uppercase in the first letter in Login & Signup screen. Username & Email input should be in lowercase in the first letter in Login & Signup screen.
Added a new flag for AppTextField - `autoCapitalization` and disable it for the above input textfields.
https://user-images.githubusercontent.com/70877098/141723680-75cf63c9-4325-43c9-8854-5755d589e46e.MP4

[#243] Fix: Username & Email input got uppercase in the first letter in Login & Signup screen

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Sources/Presentation/Modules/CreateArticle/CreateArticleView.swift
NimbleMedium/Sources/Presentation/Modules/EditArticle/EditArticleView.swift
NimbleMedium/Sources/Presentation/Views/LabeledAppTextField.swift
NimbleMedium/Sources/Presentation/Views/LabeledAppTextView.swift

Resolved #244
As a user, I want to see the input label when it's filled so that I can know which label is in Create & Edit Article screen.
- Create `LabeledAppTextField` and `LabeledAppTextView` that have a label above the input field for letting user knows which field is for.
- Apply the new fields to Create and Edit Article screens.

[#244] As a user, I want to see the input label when it's filled in Create & Edit Article screen

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
NimbleMedium/Sources/Presentation/Modules/ArticleComments/ArticleCommentsView.swift
NimbleMedium/Sources/Presentation/Views/AppTextView.swift
NimbleMedium/Sources/Presentation/Views/LabeledAppTextView.swift

Resolved #250 
- Refactor `AppTextView`
- Clear comment input when posting successfully
- Tap outside to dismiss keyboard when comment input is focused
n/a
https://user-images.githubusercontent.com/17875522/142378614-aa1fac04-465f-4c8b-a6de-61869b180e72.mov

[#250] Fix: Comment is not cleared after sending successfully and keyboard got dismissed when sending

---

NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift

Resolved #264 
Fix article content align incorrectly
n/a

[#264] Fix: Align article contents to the left for small contents in Article screen

---

NimbleMedium/Sources/Presentation/Modules/UserProfile/CreatedArticlesTab/UserProfileCreatedArticlesTab.swift
NimbleMedium/Sources/Presentation/Modules/UserProfile/FavortiedArticlesTab/UserProfileFavoritedArticlesTab.swift

Resolved #272
Fix: No Article doesn't show up in Favorite Article tab
`No article` doesn't show up cause the API returns an empty list not an error
https://user-images.githubusercontent.com/17875522/144165762-3352cd37-f9a2-4ddc-9c56-ec962b398efb.mov

[#272] Fix: Missing "No Article" text when no article for Favorite Article section in My Profile screen

---

NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift
NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileViewModel.swift

Resolved #276 
The Create Articles and Favorite Articles sections don't show up in other Author Profile screen. These sections should show up with data in other Author Profile screen like My Profile screen.
- There is no code for loading data for these sections in other Author Profile screen. Add missing code to load the data accordingly.
- Guest user case:
https://user-images.githubusercontent.com/70877098/144191379-8e5684af-0b71-4d90-beb1-85ca4bde65c1.MP4
- Authenticated user case:
https://user-images.githubusercontent.com/70877098/144191420-80375500-a6b5-4749-a17c-07c88cc6033a.MP4

[#276] Fix: Missing Create Articles and Favorite Articles sections in other Author Profile screen
