nimblehq/nimble-medium-ios

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium.xcodeproj/project.xcworkspace/contents.xcworkspacedata
NimbleMedium.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
NimbleMedium.xcodeproj/xcshareddata/xcschemes/NimbleMedium (production).xcscheme
NimbleMedium.xcodeproj/xcshareddata/xcschemes/NimbleMedium (staging).xcscheme
NimbleMedium/App.swift
NimbleMedium/Info.plist
NimbleMedium/Modules/Home/HomeView.swift
NimbleMedium/Preview Content/Preview Assets.xcassets/Contents.json
NimbleMedium/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
NimbleMedium/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
NimbleMedium/Resources/Assets.xcassets/Contents.json
NimbleMediumTests/Info.plist
NimbleMediumTests/NimbleMediumTests.swift
NimbleMediumUITests/Info.plist
NimbleMediumUITests/NimbleMediumUITests.swift

Resolved #1 
When starting a new project, the project repository foundations need to be in place for smooth application development with proper app building and running tests guidance.
- Create xcode project and folder structure
- Add staging & production schema

[#1] [Chore] Setup project - Part 2

---

.github/workflows/lint_and_unit_test.yml
NimbleMedium.xcodeproj/project.pbxproj
NimbleMediumTests/NimbleMediumTests.swift

Resolved #2 
Run lint and unit test on pushing and PR by Github Action
- Add lint and unit test workflow
- Update Project configure
Lint
Test

[#2] [Chore] Setup CI

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuView.swift

Resolved #6 
- Create the UI container layout for the left menu layout.
- Create Side Menu which covers 2/3 of the screen vertically when showing with a dark transparent layer for the remaining 1/3 of the screen.
- Create `SideMenu` module to contain left navigation menu's content
- Update `HomeView` to contain `SideMenuView` and `FeedView`

[#6] Create left navigation menu - Final

---

.github/workflows/deploy_staging.yml
.swiftlint.yml

Resolved #126 
- Upload code coverage when building in develop
- Fix CI failure
- More information about [CI issue](https://github.com/nimblehq/ios-templates/issues/189)

[#126] Setup Codecov

---

NimbleMedium.xcodeproj/project.pbxproj

Bump version to 1.0.1 for development

[chore] Bump version to 1.0.1 for development

---

.github/CODEOWNERS
NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved

Update Refresh framework with specify platforms in Package.swift
- Fork [Refresh](https://github.com/wxxsw/Refresh) framework, update and create [PR](https://github.com/wxxsw/Refresh/pull/7) to merge it into their repo

[Chore] Fix build/archive failure on any iOS device

---

NimbleMedium.xcodeproj/project.pbxproj

Bump version to 1.1.0 for development
Remove obsoleted folders

[chore] Bump version to 1.1.0 for development

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Data/NetworkAPI/Models/APIArticleResponse.swift
NimbleMedium/Sources/Data/NetworkAPI/Models/APIArticlesResponse.swift
NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/ArticleRequestConfiguration.swift
NimbleMedium/Sources/Data/Repositories/Article/ArticleRepository.swift
NimbleMedium/Sources/Domain/Repositories/Article/ArticleRepositoryProtocol.swift
NimbleMedium/Sources/Domain/UseCases/GetArticleUseCase.swift
NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMediumTests/Resources/JSON/singleArticle.json
NimbleMediumTests/Sources/Dummy/Data/Models/APIArticleResponse+Dummy.swift
NimbleMediumTests/Sources/Dummy/Data/Models/APIArticlesResponse+Dummy.swift
NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
NimbleMediumTests/Sources/Specs/Data/Repositories/ArticleRepositorySpec.swift
NimbleMediumTests/Sources/Specs/Domain/UseCases/GetArticleUseCaseSpec.swift
NimbleMediumTests/Sources/Specs/Domain/UseCases/ListArticlesUseCaseSpec.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedRow/FeedRowViewModelSpec.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift
NimbleMediumTests/Sources/Utilities/Expectation+TestableObserver.swift

Resolved #22
Add Get Article API
- Add `getArticle()` into `ArticleRepository
- Create `GetArticleUseCase`
- Rename `APIArticleResponse` to `APIArticlesResponse` to match with response which return multi articles
- Update `APIArticleResponse` to handle single article only
Request Log
```
*** Overview *** 
URL https://conduit.productionready.io/api/articles/end-to-end-testing-with-cypress-wkyqoe
Method GET
Response Code 200
Request Start Time Sep 15 2021 - 09:03:25
Duration 14s
*** Request Header *** 
User-Agent Nimble Medium - Staging/1.0.1 (co.nimblehq.nimble-medium-stag; build:1; iOS 14.5.0) Alamofire/5.4.3
Accept-Language en;q=1.0
Accept-Encoding br;q=1.0, gzip;q=0.9, deflate;q=0.8
*** Request Body *** 
-
*** Response Header *** 
x-runtime 0.060466
x-content-type-options nosniff …
```

[#22] [Backend] As a user, I can see an article details

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Data/NetworkAPI/Models/APIArticleComment.swift
NimbleMedium/Sources/Data/NetworkAPI/Models/APIArticleCommentsResponse.swift
NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/ArticleCommentRequestConfiguration.swift
NimbleMedium/Sources/Data/Repositories/ArticleComment/ArticleCommentRepository.swift
NimbleMedium/Sources/Domain/Entities/ArticleComment.swift
NimbleMedium/Sources/Domain/Repositories/ArticleComment/ArticleCommentRepositoryProtocol.swift
NimbleMedium/Sources/Domain/UseCases/GetArticleCommentsUseCase.swift
NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMediumTests/Resources/JSON/articleComments.json
NimbleMediumTests/Sources/Dummy/Data/Models/APIArticleCommentsResponse+Dummy.swift
NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
NimbleMediumTests/Sources/Specs/Data/Repositories/ArticleCommentRepositorySpec.swift
NimbleMediumTests/Sources/Specs/Domain/UseCases/GetArticleCommentsUseCaseSpec.swift

Resolved #103
Add Get Comments API
Request Log
```
*** Overview *** 
URL https://conduit.productionready.io/api/articles/article-created-by-cypress-test-12gz5t/comments
Method GET
Response Code 200
Request Start Time Sep 15 2021 - 14:02:02
Duration 1s
*** Request Header *** 
Accept-Language en;q=1.0
Accept-Encoding br;q=1.0, gzip;q=0.9, deflate;q=0.8
User-Agent Nimble Medium - Staging/1.0.1 (co.nimblehq.nimble-medium-stag; build:1; iOS 14.5.0) Alamofire/5.4.3
*** Request Body *** 
-
*** Response Header *** 
Alt-Svc h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400
x-runtime 0.061863
nel {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
x-powered-by Phusion Passenger 4.0.60
Etag W/"183b0d8cbd0b9e5a4e8a0dcf3b8bec4b"
Server cloudflare …
```

[#103] [Backend] Add Get Comments API

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Resources/Assets.xcassets/Colors/LightGray.colorset/Contents.json
NimbleMedium/Resources/Assets.xcassets/Colors/SemiLightGray.colorset/Contents.json
NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentRow/FeedCommentRow.swift
NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentsView.swift

Resolved #29 
Create comments screen UI

[#29] As a user, I see the list of comments of an article

---

NimbleMedium.xcodeproj/project.pbxproj

Bump version to 1.2.0 for development

[chore] Bump version to 1.2.0 for development

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift

Resolved #145
- Disable dragging when FeedsView disappears
- Prevent FeedsView updates when pushing to Detail and dragging to show SideMenu
n/a
https://user-images.githubusercontent.com/17875522/134865455-478b0706-f870-4e6c-9a4a-9164ea0f9601.mov

[#145] Fix: The left menu is still openable in Article Details screen by dragging the screen from left to right

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Sources/Presentation/Modules/UserProfile/ArticleList/UserProfileView+ArticleList.swift
NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift

Resolved #65
Create Created Articles List UI
- Move padding inside `ScrollView` to prevent ScrollBar is padding too

[#65] As a user, I can see the list of created articles from the profile screen when not logged in

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView.swift
NimbleMedium/Sources/Presentation/Views/FollowButton.swift

Resolved #50 
Add Follow Button into Article Detail screen
- `FollowButtonStyle` is added to prepare`dark` style in Profile screen (#72 )
| Normal | Selected |
| --- | --- |
| <img width="543" alt="Screen Shot 2021-10-11 at 14 53 50" src="https://user-images.githubusercontent.com/17875522/136753299-d20aca91-3f61-429f-bf4f-337ee46f9130.png"> | <img width="543" alt="Screen Shot 2021-10-11 at 15 14 29" src="https://user-images.githubusercontent.com/17875522/136756563-67057d1d-2d04-4dd9-823c-77eebf2c7f05.png"> |

[#50] As a user, I can toggle to update my follow status of another user from the article details screen

---

NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift
NimbleMedium/Sources/Presentation/Views/FollowButton.swift

Resolved #72 
Add Follow Button into Profile screen
n/a
| Normal | Selected |
| --- | --- |
| <img width="543" alt="Screen Shot 2021-10-11 at 15 09 06" src="https://user-images.githubusercontent.com/17875522/136756839-4225d279-6fe7-49e0-ad0b-07bdf5634868.png"> | <img width="543" alt="Screen Shot 2021-10-11 at 15 17 13" src="https://user-images.githubusercontent.com/17875522/136756778-fe870462-7452-4ea0-85c9-8c9625b581a8.png"> |

[#72] Add Follow Button intto Profile screen

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Application/App.swift
NimbleMedium/Sources/Data/NetworkAPI/RequestConfigurations/UserRequestConfiguration.swift
NimbleMedium/Sources/Data/Repositories/User/UserRepository.swift
NimbleMedium/Sources/Domain/Repositories/User/UserRepositoryProtocol.swift
NimbleMedium/Sources/Domain/UseCases/User/FollowUserUseCase.swift
NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMediumTests/Sources/Specs/Domain/UseCases/User/FollowUserUseCaseSpec.swift

Resolved #73 
Add Follow User API
It doesn't return a `Profile` model due to we only need to know success or failure
Request Log
```
*** Overview *** 
URL https://realworld-temp-api.herokuapp.com/api/profiles/markg/follow
Method POST
Response Code 200
Request Start Time Oct 12 2021 - 10:53:25
Duration 1s
*** Request Header *** 
User-Agent Nimble Medium - Staging/1.3.0 (co.nimblehq.nimble-medium-stag; build:1; iOS 14.4.0) Alamofire/5.4.4
Authorization Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNpbmh0aHVvbmdAZ21haWwuY29tIiwidXNlcm5hbWUiOiJtYXJrZyIsInBhc3N3b3JkIjoiJDJhJDEwJFgyai5sd0Q2b1Y3WXVhUGpsVXl4eC5rbmgzQU91SVNZMFFsTDJ3RkJMeTFXb3VMVFJ4YTJTIiwiYmlvIjpudWxsLCJpbWFnZSI6Imh0dHBzOi8vcmVhbHdvcmxkLXRlbXAtYXBpLmhlcm9rdWFwcC5jb20vaW1hZ2VzL3NtaWxleS1jeXJ1cy5qcGVnIiwiaWF0IjoxNjM0MDA4ND …
```

[#73] As a user, I can follow another user

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Resources/en.lproj/Localizable.strings
NimbleMedium/Sources/Presentation/Modules/CreateArticle/CreateArticleView.swift
NimbleMedium/Sources/Presentation/Modules/EditArticle/EditArticleView.swift
NimbleMedium/Sources/Presentation/Views/ArticleInputFields/ArticleInputFields.swift
NimbleMedium/Sources/Presentation/Views/ArticleInputFields/FieldType.swift

Resolved #96
After logging in successfully, the users will be able to edit their own article and see it gets updated from  the `Home` screen's global feeds or other user's following feeds.
https://user-images.githubusercontent.com/70877098/139205179-339fec7f-ba18-4e92-8782-336dbeaa8e61.mov

[#96] As a user, I can edit my own article

---

NimbleMedium.xcodeproj/project.pbxproj

Bump version to 1.4.1 for development

[chore] Bump version to 1.4.1 for development

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMedium/Sources/Constants/Constants+API.swift
NimbleMedium/Sources/Data/NetworkAPI/Core/AuthenticatedNetworkAPI.swift
NimbleMedium/Sources/Data/NetworkAPI/Core/NetworkAPI.swift
NimbleMedium/Sources/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
NimbleMedium/Sources/Data/NetworkAPI/Interceptors/CommonInterceptor.swift

Resolved #232 
- Update BE endpoint
- Create a new server in Heroku using this [backend source](https://github.com/nimblehq/laravel-realworld-example-app)
A lot of bugs when we update with stable BE, these issues will be created soon
https://user-images.githubusercontent.com/17875522/141253636-9106a0b5-0c33-49ed-b566-c7eee45250a1.mov

[#232] Verify backend stability

---

NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsTab/FeedsTabView.swift
NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift

Resolved #245 
Fix: Home screen doesn't refresh
n/a
https://user-images.githubusercontent.com/17875522/141734142-419afd8f-d797-4063-b7fe-cdaf035cdfb2.mov

[#245] Fix: Home screen doesn't refresh

---

NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift
NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileViewModel.swift

Resolved #251
Fix: Unable load created & favorited articles
n/a
https://user-images.githubusercontent.com/17875522/142556154-0029dc53-c49d-4de7-b032-c021105d7a2e.mov

[#251] Fix: Cannot load created articles and my favorited articles in my profile screen

---

NimbleMedium.xcodeproj/project.pbxproj

Bump version to 1.4.2 for development

[chore] Bump version to 1.4.2 for development

---

NimbleMedium.xcodeproj/project.pbxproj
NimbleMediumTests/Sources/Injection/Resolver+Tests.swift
Podfile.lock

Resolved #267 
Clear Xcode warnings
n/a

[#267] Clear Xcode warnings cause code is out of update

---

NimbleMedium/Sources/Data/NetworkAPI/Interceptors/AuthenticatedInterceptor.swift
NimbleMedium/Sources/Data/Repositories/Article/ArticleRepository.swift
NimbleMedium/Sources/Injection/Resolver+Injection.swift
NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailView+UIModel.swift
NimbleMedium/Sources/Presentation/Modules/ArticleDetail/ArticleDetailViewModel.swift
NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRow+UIModel.swift
NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRowViewModel.swift
NimbleMediumTests/Sources/Specs/Data/Repositories/Article/ArticleRepositorySpec.swift

Resolved #260
Fix favorite button update incorrectly
Please ignore the typo `favourite`, it will be renamed in #263
https://user-images.githubusercontent.com/17875522/143379543-d14141fd-5c71-4516-8553-a5fabd9c392d.mov

[#260] Fix: Favorite button doesn't update correctly on Home Screen

---

NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsTab/FeedsTabView.swift

Resolved #270
Resolved #271
Fix Tab bars issue in Home screen
There is a conflict between `Refresh` and `PagerTabStripView` which make these issues
https://user-images.githubusercontent.com/17875522/144017583-c04c367a-b29f-4f5b-bd55-8434d2b38e44.mov

[#270] [#271] Fix Tab bars issue in Home screen

---

NimbleMedium/Sources/Presentation/Modules/Feeds/ArticleRow/ArticleRowViewModel.swift
NimbleMedium/Sources/Presentation/Modules/UserProfile/FavortiedArticlesTab/UserProfileFavoritedArticlesTab.swift
NimbleMedium/Sources/Presentation/Modules/UserProfile/FavortiedArticlesTab/UserProfileFavoritedArticlesTabViewModel.swift
NimbleMediumTests/Sources/Specs/Presentation/Modules/UserProfile/FavoritedArticlesTab/UserProfileFavoritedArticlesTabViewModelSpec.swift

Resolved #273
Fix: Unfavorite doesnt update Favorite Article tab
Show loading indicator when toggle favorite in Favorite Articles tab
https://user-images.githubusercontent.com/17875522/144184265-19264c1f-bdd4-453e-ad44-50c7ba934f6c.mov

[#273] Fix: Unfavorite an article doesn't remove from Favorite section in My Profile

---

NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift

Resolved #278
Fix: The contents in My Profile disappear
n/a
https://user-images.githubusercontent.com/17875522/144353892-a0b13462-be33-49b0-8699-822bcea35a02.mov

[#278] Fix: The contents in My Profile disappear after going to Author Profile screen

---

NimbleMedium/Sources/Data/Repositories/User/UserRepository.swift
NimbleMediumTests/Sources/Specs/Data/Repositories/User/UserRepositorySpec.swift

Resolved #277
Fix: Follow status doesn't show consistently between Article Details screen and Author Profile screen
n/a
https://user-images.githubusercontent.com/17875522/144532825-28857854-b959-482e-840f-54d7aa34b3c9.mov

[#277] Fix: Follow status doesn't show consistently between Article Details screen and Author Profile screen
